import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, Cpu, Database, LayoutDashboard, Sparkles } from "lucide-react";
import { useLocation, useParams } from "wouter";
import { site } from "@/data/site";

const stageIcons = [LayoutDashboard, Sparkles, Cpu, Database];

export default function CaseStudy() {
  const { slug } = useParams<{ slug: string }>();
  const [, setLocation] = useLocation();
  const index = site.projects.findIndex((project) => project.slug === slug);
  const project = site.projects[index] ?? site.projects[0];
  const previous = site.projects[(index - 1 + site.projects.length) % site.projects.length];
  const next = site.projects[(index + 1) % site.projects.length];

  return (
    <div className="site-shell noise min-h-screen bg-background">
      <header className="nav-glass fixed inset-x-0 top-0 z-50">
        <div className="container-wide flex h-[76px] items-center justify-between">
          <button onClick={() => setLocation("/")} className="flex items-center gap-3 text-sm text-white"><span className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-200/50 bg-cyan-200/10 text-cyan-200">{site.brand.logoMark}</span><span className="font-extrabold">{site.brand.name}</span></button>
          <button onClick={() => setLocation("/")} className="btn-ghost"><ArrowLeft size={15} /> Back to work</button>
        </div>
      </header>

      <main>
        <section className="relative overflow-hidden border-b border-white/[.06] pb-24 pt-40"><div className="absolute inset-0 grid-bg" /><div className="hero-orb" /><div className="container-wide relative grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="eyebrow">{project.category} / {project.label}</p><h1 className="mt-7 max-w-[720px] text-[clamp(3.7rem,8vw,7.8rem)] font-extrabold leading-[.87] tracking-[-.08em] text-white">{project.title}</h1><p className="mt-7 max-w-[540px] text-lg leading-8 text-slate-300">{project.headline}</p><div className="mt-8 flex flex-wrap gap-2">{project.stack.map((tag) => <span key={tag} className="rounded-full border border-cyan-200/20 bg-cyan-200/[.06] px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.08em] text-cyan-100">{tag}</span>)}</div></div><div className={`project-visual ${project.accent} min-h-[360px] rounded-2xl border border-white/10 shadow-2xl`}><div className="visual-grid" /><span className="visual-kicker">PRODUCT VISUAL / {project.platform}</span><div className="visual-beam" /><div className="absolute bottom-10 left-10 z-[2] flex items-center gap-3 text-cyan-100"><span className="grid h-12 w-12 place-items-center rounded-xl border border-cyan-200/30 bg-cyan-200/10"><Sparkles size={22} /></span><span className="mono text-xs">IDEA → PRODUCT</span></div></div></div></section>

        <section className="section border-b border-white/[.06]"><div className="container-wide"><div className="grid gap-3 sm:grid-cols-3"><div className="glass-card p-5"><p className="mono text-[10px] text-slate-500">ROLE</p><p className="mt-3 text-sm leading-6 text-white">{project.role}</p></div><div className="glass-card p-5"><p className="mono text-[10px] text-slate-500">TIMELINE</p><p className="mt-3 text-sm leading-6 text-white">{project.timeline}</p></div><div className="glass-card p-5"><p className="mono text-[10px] text-slate-500">PLATFORM</p><p className="mt-3 text-sm leading-6 text-white">{project.platform}</p></div></div><div className="mt-24 grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">01 / The challenge</p><h2 className="section-title mt-6 text-white">Understand the<br /><span className="text-cyan-200">problem first.</span></h2></div><div><p className="max-w-[680px] text-xl leading-9 text-slate-300">{project.challenge}</p><div className="mt-10 grid gap-3 sm:grid-cols-2"><div className="glass-card p-5"><p className="mono text-[10px] text-cyan-200">WHAT WAS DIFFICULT?</p><p className="mt-3 text-sm leading-6 text-slate-400">Important signals were mixed with everyday activity, making manual attention hard to scale.</p></div><div className="glass-card p-5"><p className="mono text-[10px] text-cyan-200">WHO WAS AFFECTED?</p><p className="mt-3 text-sm leading-6 text-slate-400">People responsible for making fast, informed decisions from complex information.</p></div></div></div></div></div></section>

        <section className="section border-b border-white/[.06] bg-[#1a102a]"><div className="container-wide"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">02 / The idea</p><h2 className="section-title mt-6 text-white">Turn raw inputs<br /><span className="text-cyan-200">into a signal.</span></h2><p className="body-copy mt-6 max-w-[340px]">{project.idea}</p></div><div className="data-flow glass-card p-6 sm:p-10"><div className="grid gap-0">{["Raw data", "Analysis", "AI / logic", "Risk assessment", "Useful action"].map((stage, stageIndex) => <div key={stage} className="flex items-center gap-5"><div className="flex w-8 flex-col items-center"><span className="grid h-8 w-8 place-items-center rounded-full border border-cyan-200/60 bg-cyan-200/[.08] font-mono text-[10px] text-cyan-100">0{stageIndex + 1}</span>{stageIndex < 4 && <span className="h-12 w-px bg-gradient-to-b from-cyan-200/60 to-blue-500/20" />}</div><div className="flex flex-1 items-center justify-between border-b border-white/[.08] py-5"><span className="text-base font-bold capitalize text-white">{stage}</span>{stageIndex === 4 ? <Check size={17} className="text-cyan-200" /> : <ArrowRight size={15} className="text-slate-600" />}</div></div>)}</div></div></div></div></section>

        <section className="section border-b border-white/[.06]"><div className="container-wide"><p className="eyebrow">03 / Our approach</p><div className="mt-7 grid gap-8 md:grid-cols-[.8fr_1.2fr] md:items-end"><h2 className="section-title text-white">A process built<br /><span className="text-cyan-200">for learning.</span></h2><p className="body-copy max-w-[430px]">We move from understanding to testing in small, visible steps. That keeps the product focused and leaves room for better questions.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Understand", "Research", "Plan", "Design", "Develop", "Test", "Improve", "Deliver"].map((stage, stageIndex) => { const Icon = stageIcons[stageIndex % stageIcons.length]; return <div key={stage} className="glass-card glass-card-hover p-5"><Icon size={18} className="text-cyan-200" /><p className="mono mt-7 text-[10px] text-slate-600">0{stageIndex + 1}</p><h3 className="mt-2 text-sm font-bold text-white">{stage}</h3><p className="mt-2 text-xs leading-5 text-slate-500">A clear step that makes the next decision easier.</p></div>; })}</div></div></section>

        <section className="section border-b border-white/[.06] bg-[#1a102a]"><div className="container-wide"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">04 / The solution</p><h2 className="section-title mt-6 text-white">Build the right<br /><span className="text-cyan-200">level of detail.</span></h2></div><div><p className="max-w-[670px] text-xl leading-9 text-slate-300">{project.solution}</p><div className="mt-12 grid gap-3 sm:grid-cols-2">{[["Make it visible", "Bring important information into one calm view."], ["Make it actionable", "Help people understand what deserves attention."], ["Make it adaptable", "Keep the architecture ready for the next useful feature."], ["Make it human", "Use simple language around powerful technology."]].map(([title, detail]) => <div key={title} className="glass-card p-5"><p className="mono text-[10px] text-cyan-200">FEATURE</p><h3 className="mt-4 text-sm font-bold text-white">{title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{detail}</p></div>)}</div></div></div></div></section>

        <section className="section border-b border-white/[.06]"><div className="container-wide"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">05 / The result</p><h2 className="section-title mt-6 text-white">What we<br /><span className="text-cyan-200">achieved.</span></h2><p className="body-copy mt-6 max-w-[350px]">No invented metrics. These are the practical outcomes the product is designed to create.</p></div><div className="grid gap-3 sm:grid-cols-2">{project.outcomes.map((outcome, index) => <div key={outcome} className="glass-card p-6"><p className="mono text-[10px] text-slate-600">0{index + 1}</p><Check size={18} className="mt-9 text-cyan-200" /><h3 className="mt-5 text-base font-bold text-white">{outcome}</h3></div>)}</div></div><div className="mt-20"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Performance snapshot</p><h3 className="mt-4 text-2xl font-extrabold tracking-[-.05em] text-white">Verified metrics, when available.</h3></div><p className="max-w-[330px] text-xs leading-5 text-slate-500">Hover or focus a card to see what evidence belongs behind each figure. No numbers are shown until verified.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{project.metrics.map(([label, value, detail], index) => <article tabIndex={0} key={label} className="metric-card glass-card group relative min-h-[178px] overflow-hidden p-6"><span className="metric-sheen" /><div className="relative z-[1] flex items-start justify-between"><span className="mono text-[10px] text-slate-600">0{index + 1}</span><span className="rounded-full border border-orange-300/40 bg-orange-100/70 px-2 py-1 font-mono text-[9px] text-orange-700">PENDING</span></div><div className="relative z-[1] mt-12"><p className="mono text-[10px] text-slate-500">{label}</p><p className="mt-2 text-2xl font-extrabold tracking-[-.06em] text-primary">{value}</p><p className="metric-detail mt-3 text-xs leading-5 text-slate-600">{detail}</p></div></article>)}</div></div><div className="mt-24 grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Before</p><div className="mt-6 grid gap-2">{project.before.map((item) => <div key={item} className="rounded-lg border border-white/[.08] bg-white/[.02] px-5 py-4 text-sm text-slate-500">{item}</div>)}</div></div><div><p className="eyebrow">After</p><div className="mt-6 grid gap-2">{project.after.map((item) => <div key={item} className="rounded-lg border border-cyan-200/20 bg-cyan-200/[.04] px-5 py-4 text-sm text-cyan-100">{item}</div>)}</div></div></div></div></section>

        <section className="section border-b border-white/[.06] bg-[#1a102a]"><div className="container-wide grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">06 / What we learned</p><h2 className="section-title mt-6 text-white">Keep the lesson.<br /><span className="text-cyan-200">Build the next.</span></h2></div><div className="grid gap-5">{project.learnings.map((learning, index) => <div key={learning} className="flex gap-5 border-b border-white/[.08] pb-5"><span className="font-mono text-xs text-cyan-200">0{index + 1}</span><p className="text-lg leading-7 text-slate-300">{learning}</p></div>)}</div></div></section>

        <section className="section"><div className="container-wide text-center"><p className="eyebrow">LIKE THIS APPROACH?</p><h2 className="mx-auto mt-7 max-w-[800px] text-[clamp(3rem,7vw,6.7rem)] font-extrabold leading-[.88] tracking-[-.08em] text-white">Let’s discuss<br /><span className="text-cyan-200">your idea.</span></h2><button onClick={() => setLocation("/#contact")} className="btn-primary mt-9">Start your project <ArrowRight size={16} /></button><div className="mt-24 flex flex-col justify-between gap-5 border-t border-white/[.1] pt-6 text-left sm:flex-row"><button onClick={() => setLocation(`/case-studies/${previous.slug}`)} className="flex items-center gap-3 text-sm text-slate-400 transition-colors hover:text-cyan-200"><ChevronLeft size={16} /> Previous / {previous.title}</button><button onClick={() => setLocation(`/case-studies/${next.slug}`)} className="flex items-center gap-3 text-sm text-slate-400 transition-colors hover:text-cyan-200">Next / {next.title} <ChevronRight size={16} /></button></div></div></section>
      </main>
      <footer className="border-t border-white/[.06] bg-[#110b1c] py-10"><div className="container-wide flex flex-col justify-between gap-3 text-xs text-slate-600 sm:flex-row"><span>© {new Date().getFullYear()} {site.brand.name}. All rights reserved.</span><span>{site.brand.tagline}</span></div></footer>
    </div>
  );
}
